### ISSUE TITLE
Translation not detected

### ISSUE THREAD

**Issue by harikrishnanr994** [aspirepress/AspireUpdate#112] opened 2024-11-04 01:45 UTC
Aspirepress Update plugin did not translate to German (PR not approved), French when the language of wp was changed. 

Steps to replicate:
Install the Change the language in wp to french. 
Navigate to Dashboard-> AspirePress

Expected Result: 
The texts are shown in French.

Actual Result:
Texts are in English.

NB: Make sure Google translator do not translate the page automatically.

**Comment by asirota** [comment] 2024-11-04 02:13
@sebastienserre can you please test the main branch for French translation?

**Comment by ipajen** [comment] 2024-11-04 08:12
Confirmed it doesn't work in main bransch. I am guessing that because its there is no implementation to load the translations yet.

AI gen:
Load Text Domain Properly
Make sure your plugin is loading the text domain correctly. Use the following function in your plugin’s main file to load the language files:
`function my_plugin_load_textdomain() {
    load_plugin_textdomain( 'my-plugin', false, dirname( plugin_basename( __FILE__ ) ) . '/languages/' );
}
add_action( 'plugins_loaded', 'my_plugin_load_textdomain' );

`
This function should be added to an init or plugins_loaded hook to ensure it runs after WordPress loads.

also see ticket https://github.com/aspirepress/AspireUpdate/issues/75

**Comment by sebastienserre** [comment] 2024-11-04 08:36
It works on my side in French:

![2024-11-04_09-34](https://github.com/user-attachments/assets/aa32872b-2002-436a-96d2-5630690699b7)

From WordPress 4.6 or 4.7, WordPress is automatically loading translataion file if it respects some rules (naming, location)

**Comment by ipajen** [comment] 2024-11-04 14:43
Closing ticket as france translation is now loaded with that PR.

**Closed by ipajen** 2024-11-04 14:43 UTC
Labels: enhancement, testing
